### ISSUE TITLE
Change the nav bar text

### ISSUE THREAD

**Issue by griphaugland** [kvarteret/kvarteret.no#104]
The text in the nav-items breaks on the double words in certain view-widths.

<img width="1437" alt="Skjermbilde 2024-02-07 kl  18 18 02" src="https://github.com/kvarteret/kvarteret.no/assets/112164680/3dc02db7-b30f-427e-8d99-d4f367d52fe8">
<img width="1279" alt="Skjermbilde 2024-02-07 kl  18 18 39" src="https://github.com/kvarteret/kvarteret.no/assets/112164680/758ea33c-cc3b-4950-ac7b-80e364512ccb">

Remove "Våre" from "Våre Barer",

Remove "Oss" from "Om oss",

Remove "Oss" from "kontakt oss"

Same for English Nav bar -->

Remove "Our" from "Our Bars",

Remove "Us" from "About Us",

Remove "Us" from "Contact Us"

**Comment by mathiash98** [comment]
You guys fixed it:
<img width="1742" alt="image" src="https://github.com/kvarteret/kvarteret.no/assets/5204006/94500a02-9732-46e5-b75c-a100452edfd5">
