### ISSUE TITLE
Implementer all events knapp

### ISSUE THREAD

**Issue by TheAzack9** [kvarteret/kvarteret.no#23]
Der mangler sadly design på dette.. TODO

**Comment by Cengelsen** [comment]
Enig! https://kvarteret.no/events trenger en finere utforming, inkludert søkefeltet. Lag gjerne et utkast, om du har tid :D

**Comment by mathiash98** [comment]
Closing as we have https://github.com/kvarteret/kvarteret.no/issues/43
