### ISSUE TITLE
Fetch opening hours dynamically from cms

### ISSUE THREAD

**Issue by TheAzack9** [kvarteret/kvarteret.no#37]
Currently we fetch them when the getStaticProps runs, but this is cached per page and therefore it might not update on all pages instantly when you change it. We should fetch it dynamically instead.

To do this do we need to add an `/api/openingHours` endpoint which returns a json object of the opening hours. (It could be cached for 15 minutes or so to not kill the cms if there ever are lots of requests)
Then in the frontend do we call the endpoint (using e.g fetch) in order to get the data and then render it.

**Comment by Cengelsen** [comment]
Still relevant, @TheAzack9 ?

**Comment by mathiash98** [comment]
This is implemented some time ago
