### ISSUE TITLE
Card sections are not that mobile friendy

### ISSUE THREAD

**Issue by TheAzack9** [kvarteret/kvarteret.no#39]
The cards bleeds outside the view on mobile, figure out why and fix.

![image](https://user-images.githubusercontent.com/2140448/167255472-50b18950-e4f2-46b5-a5cc-be25189b2915.png)

**Comment by Cengelsen** [comment]
fixed in [pull request #54 ](https://github.com/kvarteret/kvarteret.no/pull/54). However, there is room for improvement, since only the css was changed.
