### ISSUE TITLE
Kvarteret.no: Picture on page conflicts with navbar

### ISSUE THREAD

**Issue by Cengelsen** [kvarteret/kvarteret.no#64]
On https://kvarteret.no/en/aktive-studenters-forening/ The picture embedded on the page, ends up between the background of the navbar and the pictures of the navbar. like so:

![feilkvart](https://user-images.githubusercontent.com/78857869/172462684-afabaaf2-7f32-4162-aa18-cface15c7303.png)

**Comment by mathiash98** [comment]
What browser are you using?

Chrome: 
![image](https://user-images.githubusercontent.com/5204006/172579969-f038c979-4152-4d8c-ab47-917816ab9369.png)

**Comment by Cengelsen** [comment]
Latest version of firefox
