### ISSUE TITLE
Kvarteret.no: Remove grey info-box underneath 360 view on room pages

### ISSUE THREAD

**Issue by Cengelsen** [kvarteret/kvarteret.no#88]
There is a request to remove the grey "Property"-section under the "360 view"-iframe on each room page. So just remove it completely. This is what i am referencing to:

![Image](https://user-images.githubusercontent.com/78857869/191534194-7ba5e9c0-1821-4ae1-8fd0-212dda92af64.png)

Do this for both norwegian and english version

**Comment by amalie-larsen** [comment]
This is now done
